baseURL = "http://localhost:1313/"
locale = "es-ES"
defaultContentLanguage = "es"
title = "PelículasData"

enableRobotsTXT = true

[taxonomies]
  decade = "decades"

[params]
  description = "Colección de películas que he visto"

[outputs]
  home = ["HTML", "RSS"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[minify]
  disableXML = true
